source 'https://rubygems.org'
gem 'flamegraph'
gem 'minitest'
gem 'parallel'
gem 'rubocop'
gem 'simplecov'
gem 'stackprof'

# support for SimpleCov Sublime Text package - comment out if not using Sublime Text with appropriate package
# gem 'simplecov-json', require: false, group: :test
